---
# tasks file for Dellos9

 - name: "Generating ECMP configuration for dellos9"
   template:
      src: dellos9_ecmp.j2
      dest: "{{ build_dir }}/ecmp9_{{ hostname }}.conf.part"
   when: (ansible_network_os is defined and ansible_network_os == "dellos9") and ((dellos_cfg_generate | default('False')) | bool)
#   notify: save config os9
   register: generate_output

 - name: "Provisioning ECMP configuration for dellos9"
   dellos9_config:
      src: dellos9_ecmp.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellos9")
#   notify: save config os9
   register: output
